### ISSUE TITLE
Reports are not generated

### ISSUE THREAD

**Issue by mDomingues** [webdriverio/wdio-allure-reporter#5] opened 2016-02-12 15:55 UTC
Hi all,

Can't get this to work with my wdio+mocha project. I´ve added the confs to the wdio configuration file but 
**allure-results** dir is empty.

```
    reporters: ['allure'],
    reporterOptions: {
        allure: {
            outputDir: 'allure-results'
        }
    },

    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
        reporter: 'wdio-allure-reporter'
    }
```
I saw in one closed issue that with mocha, is necessary to specify the reporter to the one we want. Stil.. Same results, **dot** reporter is used by default.
Dependencies:

```
"wdio-allure-reporter": "0.0.2",
"webdriverio": "3.4.0"
```

What do you think is going on ? 

Thanks :)

**Comment by dcypherthis** [comment] 2016-02-22 20:10
Also having the same issue.  Wdio v4.0.3, wdio-allure-reporter v0.0.2

**Comment by just-boris** [comment] 2016-02-22 22:05
Hello! I investigated the issue and come up with the following:

@mDomingues Wevdriver.io prior to 4.0 version can't work with external reporters. It works only with built-in ones, like `dot` but not `allure`. If you want to use Webdriver.io with Allure, consider upgrading to 4.0. I have setup example here, maybe it helps: https://github.com/just-boris/wdio-demo

**Comment by just-boris** [comment] 2016-02-22 22:06
@dcypherthis can't reproduce it, because of that issue: https://github.com/webdriverio/webdriverio/issues/1116

Could you please share some project setup?

**Comment by michaelDomingues** [comment] 2016-02-28 20:07
@just-boris , you're right. I updated `wdio` to most recent version and all is working ok.
Thanks!

**Comment by christian-bromann** [comment] 2016-04-04 17:35
@mDomingues seems that you got the allure reporter running. Closing.

**Closed by christian-bromann** 2016-04-04 17:35 UTC

**Comment by aroramayank2002** [comment] 2016-05-26 12:53
Not sure if I should log another but I can't access allure objects from within test case. allure reporting is working for me though. I have wdio version 4.0.3.
