### ISSUE TITLE
The error "Chrome not reachable" crashes the lib

### ISSUE THREAD

**Issue by serut** [webdriverio/wdio-allure-reporter#48] opened 2017-10-17 08:05 UTC
Hello,

I'm using your library, and for an unknow reason, your library receives this events and  it makes everything stop
https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L98-L99
with `command` : 
```
{
	event: 'runner:result',
	cid: '0-0',
	specs: ['/home/myproject-e2e/tests/test/specs/projectAdmin/projectUsers.spec.js'],
	requestData: {},
	requestOptions: {
		uri: {
			protocol: 'http:',
			slashes: true,
			auth: null,
			host: '127.0.0.1:4444',
			port: '4444',
			hostname: '127.0.0.1',
			hash: null,
			search: null,
			query: null,
			pathname: '/wd/hub/session/93211f43b2dcd33b094d6ad23e01019a/screenshot',
			path: '/wd/hub/session/93211f43b2dcd33b094d6ad23e01019a/screenshot',
			href: 'http://127.0.0.1:4444/wd/hub/session/93211f43b2dcd33b094d6ad23e01019a/screenshot'
		},
		json: true,
		followAllRedirects: true,
		headers: {
			Connection: 'keep-alive',
			Accept: 'application/json',
			'User-Agent': 'webdriverio/webdriverio/4.6.2'
		},
		timeout: 90000
	},
	body: {
		message: 'chrome not reachable',
		type: 'RuntimeError',
		seleniumStack: {
			status: 100,
			type: 'SelectorTimeoutError',
			message: 'Request timed out after the element was still found on the page.',
			orgStatusMessage: 'chrome not reachable\n  (Session info: chrome=61.0.3163.100)\n  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.10.0-327.22.2.el7.x86_64 x86_64)'
		}
	},
       [...]
	time: 2017 - 10 - 17 T07: 53: 25.274 Z,
	specHash: 'c235cde27f13446ba27e7b0e740d7c73'
}
```
Stacktrace:
```
/home/myproject-e2e/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at AllureReporter.<anonymous> (/home/myproject-e2e/tests/node_modules/wdio-allure-reporter/build/reporter.js:135:52)
    at emitOne (events.js:96:13)
    at AllureReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/home/myproject-e2e/tests/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.messageHandler (/home/myproject-e2e/tests/node_modules/webdriverio/build/lib/launcher.js:623:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

```

**Comment by just-boris** [comment] 2017-10-17 08:19
Looks like a duplicate of #44.

Thank you for the report, will take a look.

**Comment by serut** [comment] 2017-10-18 15:33
Yeap exactly. I use a docker image `selenium/standalone-chrome-debug` and sometimes the selenium server doesn't respond anymore, so I need to remove the container and recreate it. 

Anyway, your lib shall not fail. 

Maybe use  [lodash.isBuffer](https://lodash.com/docs/4.17.4#isBuffer) ?

**Comment by BorisOsipov** [comment] 2018-01-07 20:47
@serut I fixed this in https://github.com/webdriverio/wdio-allure-reporter/pull/56
can you verify that issue diappear and close this one?

**Comment by netmajor** [comment] 2018-01-27 17:21
@serut Please verify

**Comment by BorisOsipov** [comment] 2018-03-09 21:08
Closed as fixed.

**Closed by BorisOsipov** 2018-03-09 21:08 UTC
