### ISSUE TITLE
Annotating Allure tests

### ISSUE THREAD

**Issue by bretsherman** [webdriverio/wdio-allure-reporter#40] opened 2017-03-10 00:27 UTC
Hi, 

There seems to be support for annotating tests when using allure-mocha. However, I can't seem to find any documentation on how to do that here. Is this possible?

**Comment by just-boris** [comment] 2017-03-10 09:26
it is going to be supported very soon. 
Close this as a duplicate of #37

**Closed by just-boris** 2017-03-10 09:26 UTC
