### ISSUE TITLE
Allure not generating report for Chrome

### ISSUE THREAD

**Issue by lj9142** [webdriverio/wdio-allure-reporter#31] opened 2016-10-17 10:01 UTC
Hello,
I am using testrunner with cucumber and allure and i am trying to set my tests up for firefox and chrome so far.

The report is generated fine when the results are for firefox but for chrome i get the attached error, can someone advise how to fix this?
![error](https://cloud.githubusercontent.com/assets/22213596/19433507/ed61e00a-9458-11e6-83b2-0c418c3d9e61.PNG)

**Comment by just-boris** [comment] 2016-10-17 10:05
If you are using Cucumber test framework, your issue is duplicate of #26
if you are using Mocha, it is duplicate of #29

**Comment by lj9142** [comment] 2016-10-18 10:48
As this is only happening for Chrome, even when all the tests complete and the tests work fine for firefox, is this definitely the same issue? If so, do you know when this fix should be getting added?

**Comment by just-boris** [comment] 2016-10-18 11:07
@lj9142 so far, `wdio-allure-framework` doesn't do any browser-specific handling.

I guess that your issue occurs when some of your tests failed and finished incorrectly. To help you with fix I definitely need to know your test framework, since we have some framework specific logic in `wdio-*-adapter` family of package.

**Comment by lj9142** [comment] 2016-10-18 12:28
As far as i can see, my tests are not failing, it is saying all the test steps have passed and i had cleared down any files from broken/failed tests.

My framework is using:
- services: selenium-standalone
- framework: cucumber
- reporters: dot, allure

What other information do you need?

**Comment by lj9142** [comment] 2016-10-18 13:00
I have looked into it further and i think you are correct, it is the same issue as #26, i had a retry setup in my tests and my test was initially failing due to the website not loading quick enough in Chrome, when i amended the test to account for this, the test passed and report generated. So i will track this issue through the original one raised.

Thank you for your help, do you know when the fix for this issue should get implemented?

**Comment by BorisOsipov** [comment] 2018-03-09 21:12
>I have looked into it further and i think you are correct, it is the same issue as #26

Duplicate of https://github.com/webdriverio/wdio-allure-reporter/issues/26

**Closed by BorisOsipov** 2018-03-09 21:12 UTC
