### ISSUE TITLE
Allure report fails if at least one test fails

### ISSUE THREAD

**Issue by uandrei** [webdriverio/wdio-allure-reporter#43] opened 2017-05-12 13:05 UTC
We're using webdriver io with cucumber and allure to run our testing and generate reports. For some reason if any assertion fails, the allure report is incomplete.

When we run the allure report generate command it produces the following error:
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke method value() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
        at ru.yandex.qatools.allure.data.utils.PluginUtils.update(PluginUtils.groovy:138)
        at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin$_process_closure1.doCall(TotalPlugin.groovy:26)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin$_process_closure1.doCall(TotalPlugin.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:109)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$400(GroovyCategorySupport.java:65)
        at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:249)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:403)
        at org.codehaus.groovy.runtime.dgm$755.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:248)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin.process(TotalPlugin.groovy:25)
        at ru.yandex.qatools.allure.data.plugins.TotalPlugin.process(TotalPlugin.groovy)
        at ru.yandex.qatools.allure.data.plugins.PluginManager.process(PluginManager.groovy:84)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:68)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
        at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)`

Components used and versions:
- wdio-allure-reporter - 0.1.2
- wdio-cucumber-framework - 0.2.17
- wdio-selenium-standalone-service - 0.0.8
- wdio-spec-reporter - 0.1.0
- webdriverio - 4.8.0
- gulp-webdriver - 2.0.3

The report generation we do is using the Docker image tagged 1.4.24.RC3.

We also tried different combinations of wdio-allure-reporter and Docker images (2.0-BETA1), however all of them throw similar exceptions.

If all the tests are 100% successful, the report generation is successful.

**Comment by just-boris** [comment] 2017-05-12 13:25
Your problem should be fixed if you will use 2.0 version. It is stable now, please upgrade.

**Comment by uandrei** [comment] 2017-05-12 13:29
I've tried using the Docker image 2.0-BETA1 which has been updated 2 days ago...same result

**Comment by just-boris** [comment] 2017-05-12 13:33
Could you provide the exact error, that you have got when ran `2.0-BETA1`? It will help us to find the source of problem.

Also, summon @baev: what do you know about our docker image distribution?

**Comment by uandrei** [comment] 2017-05-12 13:36
Hi,

With 2.0-BETA1 i get the following error:
`java.lang.NullPointerException
        at org.allurefw.report.allure1.Allure1ModelConvertUtils.convertStatus(Allure1ModelConvertUtils.java:67)
        at org.allurefw.report.allure1.Allure1ResultsReader.convert(Allure1ResultsReader.java:83)
        at org.allurefw.report.allure1.Allure1ResultsReader.lambda$null$0(Allure1ResultsReader.java:65)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.allurefw.report.allure1.Allure1ResultsReader.readResults(Allure1ResultsReader.java:66)
        at org.allurefw.report.ProcessStage.lambda$readTestCases$4(ProcessStage.java:137)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.allurefw.report.ProcessStage.readTestCases(ProcessStage.java:138)
        at org.allurefw.report.ProcessStage.processData(ProcessStage.java:88)
        at org.allurefw.report.ProcessStage.run(ProcessStage.java:69)
        at org.allurefw.report.Main.generate(Main.java:72)
        at org.allurefw.report.command.ReportGenerate.run(ReportGenerate.java:41)
        at org.allurefw.report.CommandLine.main(CommandLine.java:65)`

**Comment by baev** [comment] 2017-05-12 13:43
the problem is that you have no status attribute in xml. Allure 2 should handle this situation, and display `unknown` status in the report

**Comment by baev** [comment] 2017-05-12 13:43
> @baev: what do you know about our docker image distribution?

mmm..nothing?

**Comment by uandrei** [comment] 2017-05-12 14:09
I've checked most of the XML files and it seems that all the testcases and steps have a status tag.

This is an extract of one of the XML files that contain a broken step:
`<test-case start='1494592913324' status='broken' stop='1494592913429'>
	<name>Error "Username field is not required" is displayed</name>
	<title>Error "Username field is not required" is displayed</title>
	<labels/>
	<parameters>
		<parameter kind='environment-variable' name='capabilities' value='{"browserName":"chrome"}'/>
		<parameter kind='environment-variable' name='spec files' value='["D:\\Work\\e2e\\features\\login.feature"]'/>
	</parameters>
	<steps>
		<step start='1494592913325' status='passed' stop='1494592913344'>
			<name>POST /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element</name>
			<title>POST /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element</title>
			<attachments>
				<attachment title='Request' source='ff64cb9c-6e11-4d09-a479-0f8e57b9b122-attachment.json' type='application/json' size='62'/>
				<attachment title='Response' source='6c1f248e-7f16-4207-8cfa-1dded6ee902f-attachment.json' type='application/json' size='220'/>
			</attachments>
			<steps/>
		</step>
		<step start='1494592913348' status='passed' stop='1494592913377'>
			<name>POST /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element/2/element</name>
			<title>POST /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element/2/element</title>
			<attachments>
				<attachment title='Request' source='27853044-6c8d-4f72-9eec-35ae15c3f840-attachment.json' type='application/json' size='77'/>
				<attachment title='Response' source='8e2c02e1-4b90-4cdf-84ca-df17c28f39cd-attachment.json' type='application/json' size='220'/>
			</attachments>
			<steps/>
		</step>
		<step start='1494592913387' status='passed' stop='1494592913422'>
			<name>GET /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element/3/text</name>
			<title>GET /wd/hub/session/21a71d74-b29b-40eb-982e-51a931b683bc/element/3/text</title>
			<attachments>
				<attachment title='Response' source='0a52d8ff-e887-4518-b540-05f07eca9244-attachment.json' type='application/json' size='256'/>
			</attachments>
			<steps/>
		</step>
	</steps>
	<attachments/>
	<failure>
		<message>expected 'The Username field is required.\nThe Password field is required.' to include 'Username field is not required'</message>
		<stack-trace>AssertionError: expected 'The Username field is required.\nThe Password field is required.' to include 'Username field is not required'
			at World.&lt;anonymous> (D:\Work\step_definitions\login.steps.js:46:28)
			at D:\Work\build\index.js:584:26
			at Promise.F (D:\Work\node_modules\core-js\library\modules\_export.js:35:28)
			at World.executeSync (D:\Work\node_modules\wdio-sync\build\index.js:582:12)
			at D:\Work\node_modules\wdio-sync\build\index.js:205:29</stack-trace>
	</failure>
</test-case>`

Any ideas how to fix this?

**Comment by baev** [comment] 2017-05-12 14:17
use latest Allure version https://bintray.com/qameta/generic/allure2 to generate the report. Then you need to find all the tests/steps with status `unknown`, and then you can find bad xml files, I guess

**Comment by BorisOsipov** [comment] 2018-03-09 21:10
Problem fixed in allure 2.0

**Closed by BorisOsipov** 2018-03-09 21:10 UTC
