### ISSUE TITLE
All hooks shows as broken

### ISSUE THREAD

**Issue by mandalm** [webdriverio/wdio-allure-reporter#15] opened 2016-06-03 09:09 UTC
I am using this reporter.

On console i can see no error. But when i generate report and display those i am seeing lots of broken error / warning / info.

I am using mocha as test framework. I am using dynamic testcase adding using before hook. I don't know how to fix this issue. Please help me to understand this error and solve this.

```Console Output after Test```
<img width="515" alt="screen shot 2016-06-03 at 2 34 53 pm" src="https://cloud.githubusercontent.com/assets/16209966/15774150/7c3b4676-2998-11e6-994f-46c339c8bf63.png">

```Allure Repoting UI```
<img width="1268" alt="screen shot 2016-06-03 at 2 34 39 pm" src="https://cloud.githubusercontent.com/assets/16209966/15774151/7c494d16-2998-11e6-8a0e-f94d8d86f83b.png">

Thanks and regards
Mithun Mandal

**Comment by just-boris** [comment] 2016-06-03 09:33
Hello. This is duplicate of https://github.com/webdriverio/wdio-allure-reporter/issues/13

Work on fixing that is going in #8

**Comment by christian-bromann** [comment] 2016-06-08 17:41
Closing. We are working on it to fix this.

**Closed by christian-bromann** 2016-06-08 17:41 UTC

**Comment by deepajonnala** [comment] 2016-06-08 20:56
Hi,

i upgraded to latest wdio version(4.0.9) and i am seeing this issue.Any help?

**Comment by christian-bromann** [comment] 2016-06-08 20:57
> Closing. We are working on it to fix this.

**Comment by mandalm** [comment] 2016-06-09 07:56
@christian-bromann can you keep it open until PR is merged. so that i can also close my ticket. thanks.
